name: archdemo
description: A demo project
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider:
  path:
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.1
  bloc_concurrency: ^0.2.0
  equatable: ^2.0.5
  quiver: ^3.1.0
  intl: ^0.17.0
  dio: ^4.0.6
  firebase_core: ^2.1.0
  firebase_messaging: ^14.0.2
  firebase_analytics: ^10.0.2
  firebase_crashlytics: ^3.0.2
  firebase_remote_config: ^3.0.2
  permission_handler: ^10.2.0
  flutter_slidable: ^2.0.0
  flutter_secure_storage: ^7.0.1
  connectivity_plus: ^3.0.2
  webview_flutter: ^3.0.4
  mime: ^1.0.3
  floor: ^1.3.0
  floor_generator: ^1.3.0
  async: ^2.9.0
  build_runner: ^2.2.1            # execute flutter packages pub run build_runner build lib

  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


flutter:
  uses-material-design: true

  assets:
    - assets/i18n/en.json
    - assets/images/
    - assets/icons/
    - assets/html/
    - assets/html/en_us/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
